# Generated by Django 5.1.1 on 2024-09-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CarItem',
        ),
    ]
